### ISSUE TITLE
I can't create my link

### ISSUE THREAD

**Issue by cxplay** [nchathura/One_Drive_Direct_Download_Links_Generator#1]
My link is: https://nvzwjezr-my.sharepoint.com/:v:/g/personal/me_cxplay_top/ETDW-Q4yAbFHggo9CGRJGMABbqqmqMxFSHPKJqD8C5UgYg

![2020-06-27_220111](https://user-images.githubusercontent.com/62034099/85924477-2c541f00-b8c5-11ea-8652-87799ff4a22d.png)
)

**Comment by nchathura** [comment]
Problem Solved :) You can download the **updated** version now and try it.

**Comment by cxplay** [comment]
> Problem Solved :) You can download the **updated** version now and try it.

OK，I will try it.

**Comment by cxplay** [comment]
So good!
https://nvzwjezr-my.sharepoint.com/:i:/g/personal/me_cxplay_top/EXkgvWQsH9tLq_V57SU6zvwBpUAdWruDQv-bfMR48iQTlQ?download=1
